---
- name: deploy vm from template
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars_template.yml
  tasks:
    - name: clone VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        name: "{{ vm_name }}"
        resource_pool: "{{ vcenter_resource_pool }}"
        folder: "{{ vcenter_destination_folder }}"
        template: "{{ vm_template }}"
