---
- name: Install packages on Ubuntu Server
  hosts: TestInventory
  become: true
  become_method: sudo
  tasks:
    - name: Install curl, gnupg2, software-properties-common, apt-transport-https, ca-certificates
      apt:
        name:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
